<?php
/**
 * Accueil Partikulier — structure éditoriale alignée sur le preview Manus.
 * Les annonces, villes et catégories restent issus d’Estatik ; les blocs vides
 * affichent un état éditorial honnête sans inventer de biens ou de témoignages.
 * @package Partikulier
 */
if ( ! defined( 'ABSPATH' ) ) { exit; }
get_header();

	$recent = get_posts( array(
		'post_type' => PARTIKULIER_ESTATIK_POST_TYPE,
		'post_status' => 'publish',
		'posts_per_page' => 6,
		'no_found_rows' => true,
		'orderby' => array( 'post_date', 'ID' ),
		'order' => 'DESC',
		'meta_query' => Partikulier_Dashboard::active_listing_meta_query(),
		'update_post_term_cache' => true,
		'update_post_meta_cache' => true,
	) );
	$featured = ! empty( $recent ) ? array( $recent[0] ) : array();
// Prefixe pk_home_ : card-property.php et search-form.php ecrasent $types
// (variables globales partagees par require). Bug constate au rendu :
// une seule tuile de type s'affichait, vide, apres la boucle des cartes.
$pk_home_types = get_terms( array( 'taxonomy' => PARTIKULIER_ESTATIK_TYPE_TAXONOMY, 'hide_empty' => false, 'number' => 6 ) );
$pk_home_cities = Partikulier_Geo::top_cities( 8 );
$regions = Partikulier_Geo::top_regions( 8 );
$hero_url = Partikulier_Customization::hero_url();
$hero_alt = Partikulier_Customization::hero_alt( Partikulier_Localization::translate_polylang_string( 'Maison lumineuse à vendre entre particuliers', 'Maison lumineuse à vendre entre particuliers', 'partikulier' ) );
$home = home_url( '/' );
$archive = pk_properties_archive_url();
if ( is_wp_error( $archive ) || ! is_string( $archive ) ) { $archive = home_url( '/' ); }
$deposit = pk_page_url( 'deposer', '/deposer/' );
	$pk_home_lang = class_exists( 'Partikulier_Localization' ) ? Partikulier_Localization::current_language() : 'fr';
	$tagline = Partikulier_Customization::editorial( 'home_title', Partikulier_Settings::get( 'site_tagline' ) );
	$intro = Partikulier_Customization::editorial( 'home_intro', Partikulier_Settings::get( 'site_intro' ) );
		$badge_1 = Partikulier_Customization::editorial( 'badge_1', class_exists( 'Partikulier_Localization' ) ? Partikulier_Localization::translate_polylang_string( 'Zéro commission', 'Zéro commission', 'partikulier' ) : 'Zéro commission' );
		$badge_2 = Partikulier_Customization::editorial( 'badge_2', class_exists( 'Partikulier_Localization' ) ? Partikulier_Localization::translate_polylang_string( 'Vendeur identifié', 'Vendeur identifié', 'partikulier' ) : 'Vendeur identifié' );
		$badge_3 = Partikulier_Customization::editorial( 'badge_3', class_exists( 'Partikulier_Localization' ) ? Partikulier_Localization::translate_polylang_string( 'Contact direct', 'Contact direct', 'partikulier' ) : 'Contact direct' );
?>

	<section class="pk-editorial-hero" aria-label="<?php echo esc_attr( Partikulier_Localization::translate_polylang_string( 'Recherche principale', 'Recherche principale', 'partikulier' ) ); ?>">
		<div class="pk-editorial-hero__media"><img src="<?php echo esc_url( $hero_url ); ?>" alt="<?php echo esc_attr( $hero_alt ); ?>" width="1600" height="686" fetchpriority="high" decoding="async"><div class="pk-editorial-hero__veil"></div></div>
	<div class="pk-container pk-editorial-hero__inner">
		<div class="pk-editorial-hero__copy">
			<p class="pk-editorial-kicker"><?php echo esc_html( Partikulier_Settings::get( 'topbar_text' ) ); ?></p>
			<h1><?php
			// Le preview React scinde l'accroche : 1re ligne blanche sans-serif,
			// 2e ligne en italique serif sable. On coupe sur le dernier segment
			// pour rester fidele sans imposer de balisage au texte administrable.
			$pk_parts = preg_split( '/\s+/', trim( (string) $tagline ) );
			if ( count( $pk_parts ) > 2 ) {
				$pk_tail = implode( ' ', array_slice( $pk_parts, -2 ) );
				$pk_head = implode( ' ', array_slice( $pk_parts, 0, -2 ) );
				echo esc_html( $pk_head ) . ' <span class="pk-hero-accent">' . esc_html( $pk_tail ) . '</span>';
			} else {
				echo esc_html( $tagline );
			}
			?></h1>
			<p class="pk-editorial-hero__intro"><?php echo wp_kses( $intro, array( 'a' => array( 'href' => true, 'title' => true ), 'strong' => array(), 'em' => array(), 'br' => array() ) ); ?></p>
			<div class="pk-editorial-actions"><a class="pk-btn pk-btn-primary" href="<?php echo esc_url( $deposit ); ?>"><?php echo esc_html( Partikulier_Settings::get( 'btn_deposit' ) ); ?><svg viewBox="0 0 24 24" width="15" height="15" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="M5 12h14M13 6l6 6-6 6"/></svg></a><a class="pk-btn pk-btn-light" href="<?php echo esc_url( $archive ); ?>"><?php echo esc_html( Partikulier_Settings::get( 'btn_listings' ) ); ?><svg viewBox="0 0 24 24" width="15" height="15" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><circle cx="11" cy="11" r="7"/><path d="m20 20-3.5-3.5"/></svg></a></div>
		</div>
		<div class="pk-editorial-search"><p class="pk-editorial-search__hint"><svg viewBox="0 0 24 24" width="15" height="15" fill="none" stroke="currentColor" stroke-width="1.7" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="M12 21s7-6.2 7-11a7 7 0 1 0-14 0c0 4.8 7 11 7 11z"/><circle cx="12" cy="10" r="2.6"/></svg><?php echo esc_html( Partikulier_Localization::translate_polylang_string( 'Commencez par une ville, un quartier ou un code postal.', 'Commencez par une ville, un quartier ou un code postal.', 'partikulier' ) ); ?></p><?php $variant = 'hero'; require PARTIKULIER_DIR . '/templates/parts/search-form.php'; ?><ul class="pk-hero-trust"><li><?php echo esc_html( $badge_1 ); ?></li><li><?php echo esc_html( $badge_2 ); ?></li><li><?php echo esc_html( $badge_3 ); ?></li></ul></div>
	</div>
</section>

	<section class="pk-editorial-section pk-editorial-section--featured"><div class="pk-container"><div class="pk-editorial-heading"><p class="pk-editorial-kicker"><?php echo esc_html( Partikulier_Localization::translate_polylang_string( 'Annonce à la une', 'Annonce à la une', 'partikulier' ) ); ?></p><h2><?php echo esc_html( Partikulier_Localization::translate_polylang_string( 'Des biens choisis pour leur lumière.', 'Des biens choisis pour leur lumière.', 'partikulier' ) ); ?></h2><p><?php echo esc_html( Partikulier_Localization::translate_polylang_string( 'Un accès direct aux annonces publiées par leurs propriétaires.', 'Un accès direct aux annonces publiées par leurs propriétaires.', 'partikulier' ) ); ?></p></div>
<?php if ( $featured ) : $property = $featured[0]; $img = Partikulier_AVIF::first_image( $property->ID ); $pk_featured_title = class_exists( 'Partikulier_Listing_I18n' ) ? Partikulier_Listing_I18n::title_from_post( $property, $pk_home_lang ) : get_the_title( $property ); $pk_featured_location = Partikulier_Geo::location_string( $property->ID, $pk_home_lang ); $pk_featured_url = get_permalink( $property ); if ( class_exists( 'Partikulier_Listing_URLs' ) ) { $pk_featured_url = Partikulier_Listing_URLs::filter_link( $pk_featured_url, $property ); } ?><a class="pk-editorial-feature" href="<?php echo esc_url( $pk_featured_url ); ?>"><?php if ( $img ) : ?><img src="<?php echo esc_url( $img ); ?>" width="1600" height="900" alt="<?php echo esc_attr( $pk_featured_title ); ?>" loading="lazy" decoding="async"><?php endif; ?><span class="pk-editorial-feature__veil"></span><span class="pk-editorial-feature__content"><strong><?php echo esc_html( $pk_featured_title ); ?></strong><small><?php echo esc_html( $pk_featured_location ); ?></small></span></a><?php else : ?><div class="pk-editorial-empty"><strong><?php echo esc_html( Partikulier_Localization::translate_polylang_string( 'Les premières annonces apparaîtront ici.', 'Les premières annonces apparaîtront ici.', 'partikulier' ) ); ?></strong><span><?php echo esc_html( Partikulier_Localization::translate_polylang_string( 'Déposez un bien gratuitement pour ouvrir cette sélection.', 'Déposez un bien gratuitement pour ouvrir cette sélection.', 'partikulier' ) ); ?></span><a class="pk-btn pk-btn-dark" href="<?php echo esc_url( $deposit ); ?>"><?php echo esc_html( Partikulier_Localization::translate_polylang_string( 'Déposer une annonce', 'Déposer une annonce', 'partikulier' ) ); ?></a></div><?php endif; ?></div></section>

	<section class="pk-editorial-section pk-editorial-section--tint"><div class="pk-container"><div class="pk-editorial-heading pk-editorial-heading--row"><div><p class="pk-editorial-kicker"><?php echo esc_html( Partikulier_Localization::translate_polylang_string( 'Fraîchement publiées', 'Fraîchement publiées', 'partikulier' ) ); ?></p><h2><?php echo esc_html( Partikulier_Localization::translate_polylang_string( 'Les dernières annonces', 'Les dernières annonces', 'partikulier' ) ); ?></h2><p><?php echo esc_html( Partikulier_Localization::translate_polylang_string( 'Des biens ajoutés récemment par leurs propriétaires.', 'Des biens ajoutés récemment par leurs propriétaires.', 'partikulier' ) ); ?></p></div><a class="pk-editorial-link" href="<?php echo esc_url( $archive ); ?>"><?php echo esc_html( Partikulier_Localization::translate_polylang_string( 'Voir toutes les annonces', 'Voir toutes les annonces', 'partikulier' ) ); ?> <span aria-hidden="true">→</span></a></div><?php if ( $recent ) : ?><div class="pk-editorial-cards"><?php foreach ( $recent as $property ) { require PARTIKULIER_DIR . '/templates/parts/card-property.php'; } wp_reset_postdata(); ?></div><?php else : ?><div class="pk-editorial-empty pk-editorial-empty--compact"><strong><?php echo esc_html( Partikulier_Localization::translate_polylang_string( 'Aucune annonce publiée pour le moment.', 'Aucune annonce publiée pour le moment.', 'partikulier' ) ); ?></strong><a class="pk-editorial-link" href="<?php echo esc_url( $deposit ); ?>"><?php echo esc_html( Partikulier_Localization::translate_polylang_string( 'Publier gratuitement', 'Publier gratuitement', 'partikulier' ) ); ?> <span aria-hidden="true">→</span></a></div><?php endif; ?></div></section>

	<section class="pk-editorial-section"><div class="pk-container"><div class="pk-editorial-heading"><p class="pk-editorial-kicker"><?php echo esc_html( Partikulier_Localization::translate_polylang_string( 'Trouvez votre bien', 'Trouvez votre bien', 'partikulier' ) ); ?></p><h2><?php echo esc_html( Partikulier_Localization::translate_polylang_string( 'Une recherche qui commence par le bon lieu.', 'Une recherche qui commence par le bon lieu.', 'partikulier' ) ); ?></h2><p><?php echo esc_html( Partikulier_Localization::translate_polylang_string( 'Parcourez les catégories sans bruit, puis laissez les détails vous guider.', 'Parcourez les catégories sans bruit, puis laissez les détails vous guider.', 'partikulier' ) ); ?></p></div><div class="pk-editorial-types"><?php if ( ! is_wp_error( $pk_home_types ) && $pk_home_types ) : foreach ( $pk_home_types as $term ) : ?><a href="<?php echo esc_url( pk_term_url( $term, $archive ) ); ?>" class="pk-editorial-type"><span class="pk-editorial-type__icon"><?php echo pk_type_icon( $term->slug ); // phpcs:ignore ?></span><strong><?php echo esc_html( class_exists( 'Partikulier_Listing_I18n' ) ? Partikulier_Listing_I18n::localized_type( $term->name, $pk_home_lang ) : $term->name ); ?></strong><small><?php echo esc_html( number_format_i18n( $term->count ) ); ?> <?php echo esc_html( Partikulier_Localization::translate_polylang_string( 'annonces', 'annonces', 'partikulier' ) ); ?></small></a><?php endforeach; else : foreach ( array( 'Appartement', 'Maison', 'Terrain', 'Parking', 'Immeuble', 'Local' ) as $label ) : ?><a href="<?php echo esc_url( $archive ); ?>" class="pk-editorial-type"><span class="pk-editorial-type__icon"><?php echo pk_type_icon( sanitize_title( $label ) ); // phpcs:ignore ?></span><strong><?php echo esc_html( class_exists( 'Partikulier_Localization' ) ? Partikulier_Localization::translate_polylang_string( $label, $label, 'partikulier' ) : esc_html__( $label, 'partikulier' ) ); ?></strong><small><?php echo esc_html( class_exists( 'Partikulier_Localization' ) ? Partikulier_Localization::translate_polylang_string( 'Explorer', 'Explorer', 'partikulier' ) : __( 'Explorer', 'partikulier' ) ); ?></small></a><?php endforeach; endif; ?></div></div></section>

	<section class="pk-editorial-section pk-editorial-section--rental"><div class="pk-container"><div class="pk-editorial-rental"><div><p class="pk-editorial-kicker"><?php echo esc_html( Partikulier_Localization::translate_polylang_string( 'À louer directement', 'À louer directement', 'partikulier' ) ); ?></p><h2><?php echo esc_html( Partikulier_Localization::translate_polylang_string( 'Un appartement avec vue sur le large.', 'Un appartement avec vue sur le large.', 'partikulier' ) ); ?></h2><p><?php echo esc_html( Partikulier_Localization::translate_polylang_string( 'Découvrez les biens qui privilégient la lumière, l’espace et le contact direct.', 'Découvrez les biens qui privilégient la lumière, l’espace et le contact direct.', 'partikulier' ) ); ?></p><a class="pk-btn pk-btn-dark" href="<?php echo esc_url( $archive ); ?>"><?php echo esc_html( Partikulier_Localization::translate_polylang_string( 'Rechercher un bien', 'Rechercher un bien', 'partikulier' ) ); ?> <span aria-hidden="true">→</span></a></div><div class="pk-editorial-rental__shape" aria-hidden="true"></div></div></div></section>

	<section class="pk-editorial-section"><div class="pk-container pk-editorial-places"><div><p class="pk-editorial-kicker"><?php echo esc_html( Partikulier_Localization::translate_polylang_string( 'Proche de chez vous', 'Proche de chez vous', 'partikulier' ) ); ?></p><h2><?php echo esc_html( Partikulier_Localization::translate_polylang_string( 'Trouvez un bien dans votre ville.', 'Trouvez un bien dans votre ville.', 'partikulier' ) ); ?></h2><p><?php echo esc_html( Partikulier_Localization::translate_polylang_string( 'Les quartiers et villes sont indexés pour vous aider à trouver plus vite.', 'Les quartiers et villes sont indexés pour vous aider à trouver plus vite.', 'partikulier' ) ); ?></p><a class="pk-btn pk-btn-dark" href="<?php echo esc_url( $archive ); ?>"><?php echo esc_html( Partikulier_Localization::translate_polylang_string( 'Explorer les annonces', 'Explorer les annonces', 'partikulier' ) ); ?></a></div><div class="pk-editorial-place-list"><?php if ( $pk_home_cities ) : foreach ( $pk_home_cities as $city ) : ?><a href="<?php echo esc_url( pk_term_url( $city, $archive ) ); ?>"><span><?php echo esc_html( class_exists( 'Partikulier_Listing_I18n' ) ? Partikulier_Listing_I18n::localized_place( $city->name, $pk_home_lang ) : $city->name ); ?></span><small><?php echo esc_html( number_format_i18n( $city->count ) ); ?></small><span aria-hidden="true">→</span></a><?php endforeach; else : ?><p class="pk-editorial-empty-text"><?php echo esc_html( Partikulier_Localization::translate_polylang_string( 'Les villes apparaîtront dès les premières annonces.', 'Les villes apparaîtront dès les premières annonces.', 'partikulier' ) ); ?></p><?php endif; ?></div></div></section>

	<section class="pk-editorial-region-band"><div class="pk-container pk-editorial-region-band__inner"><div><p class="pk-editorial-kicker"><?php echo esc_html( Partikulier_Localization::translate_polylang_string( 'Par région', 'Par région', 'partikulier' ) ); ?></p><h2><?php echo esc_html( Partikulier_Localization::translate_polylang_string( 'Partout au Maroc.', 'Partout au Maroc.', 'partikulier' ) ); ?></h2></div><div class="pk-editorial-region-list"><?php if ( $regions ) : foreach ( $regions as $region ) : ?><a href="<?php echo esc_url( pk_term_url( $region, $archive ) ); ?>"><?php echo esc_html( class_exists( 'Partikulier_Listing_I18n' ) ? Partikulier_Listing_I18n::localized_place( $region->name, $pk_home_lang ) : $region->name ); ?> <span aria-hidden="true">→</span></a><?php endforeach; else : ?><a href="<?php echo esc_url( $archive ); ?>"><?php echo esc_html( Partikulier_Localization::translate_polylang_string( 'Toutes les annonces', 'Toutes les annonces', 'partikulier' ) ); ?> <span aria-hidden="true">→</span></a><?php endif; ?></div></div></section>

<?php get_footer();