<?php
/**
 * Catalogue de repli du formulaire de dépôt (lot B6, découpe REG-3 de
 * class-localization.php — 990 lignes historiques).
 *
 * Libellés du formulaire de dépôt utilisés comme repli déterministe lorsque
 * Polylang n'a pas encore de traduction enregistrée pour une chaîne. Le
 * texte libre saisi par le propriétaire n'est jamais traduit ici. Le contenu
 * des entrées est déplacé VERBATIM — l'empreinte du corpus gelé avant
 * découpe (REG-3, lot B6) doit rester identique après le lot.
 *
 * Lot C2 (extinction) : la propriété du catalogue passe au plugin
 * partikulier-core 2.8+ (\Partikulier\Core\Domain\I18n\FormsDictionary,
 * port VERBATIM prouvé par contrat C2A-003) — ces données côté thème sont
 * DORMANTES : servies uniquement par le repli local quand le plugin est
 * absent (REG-5) et lues par le gel de corpus (empreinte de service
 * d71b57fa…, diff nul exigé). Le retrait physique relève du lot C4.
 *
 * @package Partikulier
 */

if ( ! defined( 'ABSPATH' ) ) {
        return;
}

trait Partikulier_Localization_Forms {

                /**
                 * Libellés du formulaire de dépôt utilisés comme repli déterministe lorsque
                 * Polylang n’a pas encore de traduction enregistrée pour une chaîne.
                 * Le texte libre saisi par le propriétaire n’est jamais traduit ici.
                 *
                 * @return array<string,array<string,string>>
                 */
                public static function form_translations() {
                return array(
                                '1er étage' => array( 'fr' => '1er étage', 'en' => '1st floor', 'ar' => 'الطابق الأول' ),
                                'e étage' => array( 'fr' => 'e étage', 'en' => 'th floor', 'ar' => 'الطابق' ),
                                '%d%s étage' => array( 'fr' => '%d%s étage', 'en' => '%d%s floor', 'ar' => 'الطابق %d' ),
                                '1 salon' => array( 'fr' => '1 salon', 'en' => '1 living room', 'ar' => 'صالون واحد' ),
                                '2 salons' => array( 'fr' => '2 salons', 'en' => '2 living rooms', 'ar' => 'صالونان' ),
                                '3 salons ou plus' => array( 'fr' => '3 salons ou plus', 'en' => '3 living rooms or more', 'ar' => '3 صالونات أو أكثر' ),
                                '1 salle de bains' => array( 'fr' => '1 salle de bains', 'en' => '1 bathroom', 'ar' => 'حمام واحد' ),
                                '2 salles de bains' => array( 'fr' => '2 salles de bains', 'en' => '2 bathrooms', 'ar' => 'حمامات' ),
                                '3 salles de bains ou plus' => array( 'fr' => '3 salles de bains ou plus', 'en' => '3 bathrooms or more', 'ar' => '3 حمامات أو أكثر' ),
                                'Recherche principale' => array( 'fr' => 'Recherche principale', 'en' => 'Main search', 'ar' => 'البحث الرئيسي' ),
                                'Annonce à la une' => array( 'fr' => 'Annonce à la une', 'en' => 'Featured listing', 'ar' => 'إعلان مميز' ),
                                'Des biens choisis pour leur lumière.' => array( 'fr' => 'Des biens choisis pour leur lumière.', 'en' => 'Properties chosen for their light.', 'ar' => 'عقارات مختارة لجمال إضاءتها.' ),
                                'Un accès direct aux annonces publiées par leurs propriétaires.' => array( 'fr' => 'Un accès direct aux annonces publiées par leurs propriétaires.', 'en' => 'Direct access to listings published by owners.', 'ar' => 'وصول مباشر للإعلانات المنشورة من قبل أصحابها.' ),
                                'Fraîchement publiées' => array( 'fr' => 'Fraîchement publiées', 'en' => 'Freshly published', 'ar' => 'نشرت حديثاً' ),
                                'Les dernières annonces' => array( 'fr' => 'Les dernières annonces', 'en' => 'Latest listings', 'ar' => 'آخر الإعلانات' ),
                                'Des biens ajoutés récemment par leurs propriétaires.' => array( 'fr' => 'Des biens ajoutés récemment par leurs propriétaires.', 'en' => 'Properties recently added by their owners.', 'ar' => 'عقارات أضيفت مؤخراً من قبل أصحابها.' ),
                                'Voir toutes les annonces' => array( 'fr' => 'Voir toutes les annonces', 'en' => 'View all listings', 'ar' => 'مشاهدة جميع الإعلانات' ),
                                'Trouvez votre bien' => array( 'fr' => 'Trouvez votre bien', 'en' => 'Find your property', 'ar' => 'جد عقارك' ),
                                'Une recherche qui commence par le bon lieu.' => array( 'fr' => 'Une recherche qui commence par le bon lieu.', 'en' => 'A search that starts with the right place.', 'ar' => 'بحث يبدأ بالمكان المناسب.' ),
                                'Parcourez les catégories sans bruit, puis laissez les détails vous guider.' => array( 'fr' => 'Parcourez les catégories sans bruit, puis laissez les détails vous guider.', 'en' => 'Browse categories without noise, then let details guide you.', 'ar' => 'تصفح الفئات بكل هدوء، واترك التفاصيل توجهك.' ),
                                'À louer directement' => array( 'fr' => 'À louer directement', 'en' => 'For rent directly', 'ar' => 'للكراء المباشر' ),
                                'Un appartement avec vue sur le large.' => array( 'fr' => 'Un appartement avec vue sur le large.', 'en' => 'An apartment with a view of the open sea.', 'ar' => 'شقة مطلة على البحر.' ),
                                'Découvrez les biens qui privilégient la lumière, l’espace et le contact direct.' => array( 'fr' => 'Découvrez les biens qui privilégient la lumière, l’espace et le contact direct.', 'en' => 'Discover properties that prioritize light, space and direct contact.', 'ar' => 'اكتشف العقارات التي تعطي الأولوية للإضاءة، المساحة والتواصل المباشر.' ),
                                'Rechercher un bien' => array( 'fr' => 'Rechercher un bien', 'en' => 'Search for a property', 'ar' => 'البحث عن عقار' ),
                                'Proche de chez vous' => array( 'fr' => 'Proche de chez vous', 'en' => 'Near you', 'ar' => 'بالقرب منك' ),
                                'Trouvez un bien dans votre ville.' => array( 'fr' => 'Trouvez un bien dans votre ville.', 'en' => 'Find a property in your city.', 'ar' => 'جد عقاراً في مدينتك.' ),
                                'Les quartiers et villes sont indexés pour vous aider à trouver plus vite.' => array( 'fr' => 'Les quartiers et villes sont indexés pour vous aider à trouver plus vite.', 'en' => 'Neighborhoods and cities are indexed to help you find faster.', 'ar' => 'الأحياء والمدن مفهرسة لمساعدتك في العثور بسرعة.' ),
                                'Explorer les annonces' => array( 'fr' => 'Explorer les annonces', 'en' => 'Explore listings', 'ar' => 'استكشاف الإعلانات' ),
                                'Par région' => array( 'fr' => 'Par région', 'en' => 'By region', 'ar' => 'حسب الجهة' ),
                                'Partout au Maroc.' => array( 'fr' => 'Partout au Maroc.', 'en' => 'Throughout Morocco.', 'ar' => 'في جميع أنحاء المغرب.' ),
                                'Aide' => array( 'fr' => 'Aide', 'en' => 'Help', 'ar' => 'مساعدة' ),
                                        'Maison lumineuse à vendre entre particuliers' => array( 'fr' => 'Maison lumineuse à vendre entre particuliers', 'en' => 'Bright house for sale between individuals', 'ar' => 'منزل مشرق للبيع بين الأفراد' ),
                                        'Choisissez un quartier' => array( 'fr' => 'Choisissez un quartier', 'en' => 'Choose a neighborhood', 'ar' => 'اختر الحي' ),
                                        'Le catalogue direct' => array( 'fr' => 'Le catalogue direct', 'en' => 'The direct catalog', 'ar' => 'كتالوج مباشر' ),
                                        'Des biens publiés directement par leurs propriétaires.' => array( 'fr' => 'Des biens publiés directement par leurs propriétaires.', 'en' => 'Properties published directly by their owners.', 'ar' => 'عقارات منشورة مباشرة من قبل أصحابها.' ),
                                        'Localisation d’abord' => array( 'fr' => 'Localisation d’abord', 'en' => 'Location first', 'ar' => 'الموقع أولاً' ),
                                        'Action' => array( 'fr' => 'Action', 'en' => 'Action', 'ar' => 'العملية' ),
                                        'Budget maximum' => array( 'fr' => 'Budget maximum', 'en' => 'Maximum budget', 'ar' => 'الميزانية القصوى' ),
                                        'Villes populaires' => array( 'fr' => 'Villes populaires', 'en' => 'Popular cities', 'ar' => 'المدن الأكثر شعبية' ),
                                        'MAD max' => array( 'fr' => 'MAD max', 'en' => 'MAD max', 'ar' => 'الحد الأقصى بالدرهم' ),
                                        'Budget maximum en MAD' => array( 'fr' => 'Budget maximum en MAD', 'en' => 'Maximum budget in MAD', 'ar' => 'الميزانية القصوى بالدرهم' ),
                                        'Aucune annonce ne correspond à votre recherche.' => array( 'fr' => 'Aucune annonce ne correspond à votre recherche.', 'en' => 'No listing matches your search.', 'ar' => 'لا يوجد إعلان يطابق بحثك.' ),
                                        'Essayez d\'élargir vos critères ou consultez les villes populaires.' => array( 'fr' => 'Essayez d\'élargir vos critères ou consultez les villes populaires.', 'en' => 'Try to broaden your criteria or check popular cities.', 'ar' => 'حاول توسيع معاييرك أو تحقق من المدن الأكثر شعبية.' ),
                                        'Publier gratuitement' => array( 'fr' => 'Publier gratuitement', 'en' => 'Publish for free', 'ar' => 'نشر مجاني' ),
                                        'Toutes les annonces' => array( 'fr' => 'Toutes les annonces', 'en' => 'All listings', 'ar' => 'جميع الإعلانات' ),
                                        'Propriétaire' => array( 'fr' => 'Propriétaire', 'en' => 'Owner', 'ar' => 'المالك' ),
                                        '/ mois' => array( 'fr' => '/ mois', 'en' => '/ month', 'ar' => '/ شهر' ),
                                        'Ajouter aux favoris' => array( 'fr' => 'Ajouter aux favoris', 'en' => 'Add to favorites', 'ar' => 'إضافة إلى المفضلة' ),
                                        'Partager cette annonce' => array( 'fr' => 'Partager cette annonce', 'en' => 'Share this listing', 'ar' => 'مشاركة هذا الإعلان' ),
                                        'Caractéristiques' => array( 'fr' => 'Caractéristiques', 'en' => 'Features', 'ar' => 'الخصائص' ),
                                        'Oui' => array( 'fr' => 'Oui', 'en' => 'Yes', 'ar' => 'نعم' ),
                                        'Non' => array( 'fr' => 'Non', 'en' => 'No', 'ar' => 'لا' ),
                                        'Surface' => array( 'fr' => 'Surface', 'en' => 'Area', 'ar' => 'المساحة' ),
                                        'Chambres' => array( 'fr' => 'Chambres', 'en' => 'Bedrooms', 'ar' => 'غرف النوم' ),
                                        'Salons' => array( 'fr' => 'Salons', 'en' => 'Living rooms', 'ar' => 'الصالات' ),
                                        'Salles de bains' => array( 'fr' => 'Salles de bains', 'en' => 'Bathrooms', 'ar' => 'حمامات' ),
                                        'Terrasse' => array( 'fr' => 'Terrasse', 'en' => 'Terrace', 'ar' => 'تراس' ),
                                        'Parkings' => array( 'fr' => 'Parkings', 'en' => 'Parking', 'ar' => 'مواقف سيارات' ),
                                        'Étage' => array( 'fr' => 'Étage', 'en' => 'Floor', 'ar' => 'الطابق' ),
                                        'Année de construction' => array( 'fr' => 'Année de construction', 'en' => 'Year built', 'ar' => 'سنة البناء' ),
                                        'Classe énergie' => array( 'fr' => 'Classe énergie', 'en' => 'Energy class', 'ar' => 'فئة الطاقة' ),
                                        'Description' => array( 'fr' => 'Description', 'en' => 'Description', 'ar' => 'الوصف' ),
                                        'Contact sécurisé' => array( 'fr' => 'Contact sécurisé', 'en' => 'Secure contact', 'ar' => 'اتصال آمن' ),
                                        'Intéressé par ce bien ?' => array( 'fr' => 'Intéressé par ce bien ?', 'en' => 'Interested in this property?', 'ar' => 'مهتم بهذا العقار؟' ),
                                        'Envoyez cette annonce sur WhatsApp. Après vérification de votre demande, nous vous transmettons les coordonnées du propriétaire.' => array( 'fr' => 'Envoyez cette annonce sur WhatsApp. Après vérification de votre demande, nous vous transmettons les coordonnées du propriétaire.', 'en' => 'Send this listing on WhatsApp. After verification of your request, we will send you the owner\'s contact details.', 'ar' => 'أرسل هذا الإعلان على واتساب. بعد التحقق من طلبك، سنقوم بتزويدك بمعلومات الاتصال الخاصة بالمالك.' ),
                                        'Contact transmis après contrôle' => array( 'fr' => 'Contact transmis après contrôle', 'en' => 'Contact transmitted after verification', 'ar' => 'يتم إرسال معلومات الاتصال بعد التحقق' ),
                                        'Demander sur WhatsApp' => array( 'fr' => 'Demander sur WhatsApp', 'en' => 'Request on WhatsApp', 'ar' => 'الطلب عبر واتساب' ),
                                        'Vos critères sont enregistrés pour vérifier la demande. Les annonces similaires ne sont envoyées qu’avec votre accord explicite.' => array( 'fr' => 'Vos critères sont enregistrés pour vérifier la demande. Les annonces similaires ne sont envoyées qu’avec votre accord explicite.', 'en' => 'Your criteria are recorded to verify the request. Similar listings are only sent with your explicit agreement.', 'ar' => 'يتم تسجيل معاييرك للتحقق من الطلب. لا يتم إرسال إعلانات مماثلة إلا بموافقتك الصريحة.' ),
                                        'Voir les autres annonces dans cette ville' => array( 'fr' => 'Voir les autres annonces dans cette ville', 'en' => 'See other listings in this city', 'ar' => 'مشاهدة الإعلانات الأخرى في هذه المدينة' ),
                                        'Dans la même ville' => array( 'fr' => 'Dans la même ville', 'en' => 'In the same city', 'ar' => 'في نفس المدينة' ),
                                        'Voir aussi à %s' => array( 'fr' => 'Voir aussi à %s', 'en' => 'See also in %s', 'ar' => 'شاهد أيضاً في %s' ),
                                        'Tout voir' => array( 'fr' => 'Tout voir', 'en' => 'See all', 'ar' => 'مشاهدة الكل' ),
                                        'Maison lumineuse à vendre entre particuliers' => array( 'fr' => 'Maison lumineuse à vendre entre particuliers', 'en' => 'Bright house for sale by owner', 'ar' => 'منزل مشرق للبيع من طرف صاحبه' ),
                                        'Explorer' => array( 'fr' => 'Explorer', 'en' => 'Explore', 'ar' => 'استكشاف' ),
                                        'Appartement' => array( 'fr' => 'Appartement', 'en' => 'Apartment', 'ar' => 'شقة' ),
                                        'Maison' => array( 'fr' => 'Maison', 'en' => 'House', 'ar' => 'منزل' ),
                                        'Terrain' => array( 'fr' => 'Terrain', 'en' => 'Land', 'ar' => 'أرض' ),
                                        'Parking' => array( 'fr' => 'Parking', 'en' => 'Parking', 'ar' => 'موقف سيارات' ),
                                        'Immeuble' => array( 'fr' => 'Immeuble', 'en' => 'Building', 'ar' => 'عمارة' ),
                                        'Local' => array( 'fr' => 'Local', 'en' => 'Commercial', 'ar' => 'محل تجاري' ),
                                        'Caractéristiques' => array( 'fr' => 'Caractéristiques', 'en' => 'Features', 'ar' => 'المميزات' ),
                                        'Description' => array( 'fr' => 'Description', 'en' => 'Description', 'ar' => 'الوصف' ),
                                        'Demander sur WhatsApp' => array( 'fr' => 'Demander sur WhatsApp', 'en' => 'Ask on WhatsApp', 'ar' => 'الطلب عبر واتساب' ),
                                        'Chambres' => array( 'fr' => 'Chambres', 'en' => 'Bedrooms', 'ar' => 'غرف النوم' ),
                                        'Salons' => array( 'fr' => 'Salons', 'en' => 'Living rooms', 'ar' => 'صالونات' ),
                                        'Salles de bains' => array( 'fr' => 'Salles de bains', 'en' => 'Bathrooms', 'ar' => 'حمامات' ),
                                        'Parkings' => array( 'fr' => 'Parkings', 'en' => 'Parking spaces', 'ar' => 'مواقف السيارات' ),
                                        'Étage' => array( 'fr' => 'Étage', 'en' => 'Floor', 'ar' => 'الطابق' ),
                                        'Année de construction' => array( 'fr' => 'Année de construction', 'en' => 'Year built', 'ar' => 'سنة البناء' ),
                                        'Classe énergie' => array( 'fr' => 'Classe énergie', 'en' => 'Energy class', 'ar' => 'فئة الطاقة' ),
                                        'Contact sécurisé' => array( 'fr' => 'Contact sécurisé', 'en' => 'Secure contact', 'ar' => 'اتصال آمن' ),
                                        'Intéressé par ce bien ?' => array( 'fr' => 'Intéressé par ce bien ?', 'en' => 'Interested in this property?', 'ar' => 'مهتم بهذا العقار؟' ),
                                        'Envoyez cette annonce sur WhatsApp. Après vérification de votre demande, nous vous transmettons les coordonnées du propriétaire.' => array( 'fr' => 'Envoyez cette annonce sur WhatsApp. Après vérification de votre demande, nous vous transmettons les coordonnées du propriétaire.', 'en' => 'Send this listing on WhatsApp. After verification of your request, we will send you the owner\'s contact details.', 'ar' => 'أرسل هذا الإعلان عبر واتساب. بعد التحقق من طلبك، سنزودك ببيانات اتصال المالك.' ),
                                        'Cette annonce ne reçoit plus de contacts.' => array( 'fr' => 'Cette annonce ne reçoit plus de contacts.', 'en' => 'This listing no longer accepts contacts.', 'ar' => 'هذا الإعلان لم يعد يستقبل اتصالات.' ),
                                        'Envoyez-nous cette annonce sur WhatsApp. Après contrôle de votre demande, nous vous transmettons les coordonnées du propriétaire.' => array( 'fr' => 'Envoyez-nous cette annonce sur WhatsApp. Après contrôle de votre demande, nous vous transmettons les coordonnées du propriétaire.', 'en' => 'Send us this listing on WhatsApp. After verification of your request, we will send you the owner\'s contact details.', 'ar' => 'أرسل لنا هذا الإعلان عبر واتساب. بعد التحقق من طلبك، سنزودك ببيانات اتصال المالك.' ),
                                        'Vos critères seront demandés sur WhatsApp. Les annonces similaires ne sont envoyées qu’avec votre accord explicite.' => array( 'fr' => 'Vos critères seront demandés sur WhatsApp. Les annonces similaires ne sont envoyées qu’avec votre accord explicite.', 'en' => 'Your criteria will be requested on WhatsApp. Similar listings are only sent with your explicit agreement.', 'ar' => 'سيتم طلب معاييرك عبر واتساب. لا يتم إرسال إعلانات مماثلة إلا بموافقتك الصريحة.' ),
                                        'Vos critères sont vérifiés avant transmission des coordonnées.' => array( 'fr' => 'Vos critères sont vérifiés avant transmission des coordonnées.', 'en' => 'Your criteria are verified before transmitting contact details.', 'ar' => 'يتم التحقق من معاييرك قبل إرسال بيانات الاتصال.' ),
                                        'Dans la même ville' => array( 'fr' => 'Dans la même ville', 'en' => 'In the same city', 'ar' => 'في نفس المدينة' ),
                                        'Voir aussi à %s' => array( 'fr' => 'Voir aussi à %s', 'en' => 'See also in %s', 'ar' => 'شاهد أيضاً في %s' ),
                                        'Prix sur demande' => array( 'fr' => 'Prix sur demande', 'en' => 'Price on request', 'ar' => 'السعر عند الطلب' ),
                                        'Aperçu rapide' => array( 'fr' => 'Aperçu rapide', 'en' => 'Quick view', 'ar' => 'عرض سريع' ),
                                        'Composition' => array( 'fr' => 'Composition', 'en' => 'Composition', 'ar' => 'التكوين' ),
                                        'Voir l\'annonce' => array( 'fr' => 'Voir l\'annonce', 'en' => 'View listing', 'ar' => 'عرض الإعلان' ),
                                        'Bien' => array( 'fr' => 'Bien', 'en' => 'Property', 'ar' => 'عقار' ),
                                        '1 chambre' => array( 'fr' => '1 chambre', 'en' => '1 bedroom', 'ar' => 'غرفة نوم واحدة' ),
                                        '2 chambres' => array( 'fr' => '2 chambres', 'en' => '2 bedrooms', 'ar' => 'غرفتا نوم' ),
                                        '1 salon' => array( 'fr' => '1 salon', 'en' => '1 living room', 'ar' => 'صالون واحد' ),
                                        '2 salons' => array( 'fr' => '2 salons', 'en' => '2 living rooms', 'ar' => 'صالونان' ),
                                        '1 salle de bains' => array( 'fr' => '1 salle de bains', 'en' => '1 bathroom', 'ar' => 'حمام واحد' ),
                                        '2 salles de bains' => array( 'fr' => '2 salles de bains', 'en' => '2 bathrooms', 'ar' => 'حمامات' ),
                                        '3 chambres ou plus' => array( 'fr' => '3 chambres ou plus', 'en' => '3 or more bedrooms', 'ar' => '3 غرف نوم أو أكثر' ),
                                        '3 salons ou plus' => array( 'fr' => '3 salons ou plus', 'en' => '3 or more living rooms', 'ar' => '3 صالونات أو أكثر' ),
                                        '3 salles de bains ou plus' => array( 'fr' => '3 salles de bains ou plus', 'en' => '3 or more bathrooms', 'ar' => '3 حمامات أو أكثر' ),
                                        'Studio' => array( 'fr' => 'Studio', 'en' => 'Studio', 'ar' => 'استوديو' ),
                                        'Pièce principale' => array( 'fr' => 'Pièce principale', 'en' => 'Main room', 'ar' => 'الغرفة الرئيسية' ),
                                        'Commencez par une ville, un quartier ou un code postal.' => array( 'fr' => 'Commencez par une ville, un quartier ou un code postal.', 'en' => 'Start with a city, neighborhood, or zip code.', 'ar' => 'ابدأ بمدينة أو حي أو رمز بريدي.' ),
                                        'annonces' => array( 'fr' => 'annonces', 'en' => 'listings', 'ar' => 'إعلانات' ),
                                        'Questions fréquentes' => array( 'fr' => 'Questions fréquentes', 'en' => 'FAQ', 'ar' => 'الأسئلة الشائعة' ),
                                        'Contactez-nous' => array( 'fr' => 'Contactez-nous', 'en' => 'Contact us', 'ar' => 'اتصل بنا' ),
                                        'Mentions légales' => array( 'fr' => 'Mentions légales', 'en' => 'Legal notice', 'ar' => 'إشعار قانوني' ),
                                        'Maroc' => array( 'fr' => 'Maroc', 'en' => 'Morocco', 'ar' => 'المغرب' ),
                                'Titre de l’annonce *' => array( 'fr' => 'Titre de l’annonce *', 'en' => 'Listing title *', 'ar' => 'عنوان الإعلان *' ),
                        'Ex : Appartement lumineux 3 pièces avec balcon' => array( 'fr' => 'Ex : Appartement lumineux 3 pièces avec balcon', 'en' => 'E.g. Bright 3-bedroom apartment with balcony', 'ar' => 'مثال: شقة مشرقة بثلاث غرف مع شرفة' ),
                        'Vous souhaitez' => array( 'fr' => 'Vous souhaitez', 'en' => 'You want to', 'ar' => 'أرغب في' ),
                        'Type de bien' => array( 'fr' => 'Type de bien', 'en' => 'Property type', 'ar' => 'نوع العقار' ),
                                'Prix (MAD)' => array( 'fr' => 'Prix (MAD)', 'en' => 'Price (MAD)', 'ar' => 'السعر (درهم)' ),
                        'Ex : 245000' => array( 'fr' => 'Ex : 245000', 'en' => 'E.g. 245000', 'ar' => 'مثال: 245000' ),
                        'Ville' => array( 'fr' => 'Ville', 'en' => 'City', 'ar' => 'المدينة' ),
                        'Choisir une ville…' => array( 'fr' => 'Choisir une ville…', 'en' => 'Choose a city…', 'ar' => 'اختر مدينة…' ),
                        'Surface (m²)' => array( 'fr' => 'Surface (m²)', 'en' => 'Area (m²)', 'ar' => 'المساحة (م²)' ),
                        'Nombre de chambres' => array( 'fr' => 'Nombre de chambres', 'en' => 'Bedrooms', 'ar' => 'عدد غرف النوم' ),
                        'Choisir…' => array( 'fr' => 'Choisir…', 'en' => 'Choose…', 'ar' => 'اختر…' ),
                        'Studio / 0 chambre' => array( 'fr' => 'Studio / 0 chambre', 'en' => 'Studio / 0 bedrooms', 'ar' => 'استوديو / دون غرفة نوم' ),
                        '1 chambre' => array( 'fr' => '1 chambre', 'en' => '1 bedroom', 'ar' => 'غرفة نوم واحدة' ),
                        '2 chambres' => array( 'fr' => '2 chambres', 'en' => '2 bedrooms', 'ar' => 'غرفتا نوم' ),
                        '3 chambres ou plus' => array( 'fr' => '3 chambres ou plus', 'en' => '3 bedrooms or more', 'ar' => '3 غرف نوم أو أكثر' ),
                        'Nombre de salons' => array( 'fr' => 'Nombre de salons', 'en' => 'Living rooms', 'ar' => 'عدد غرف الجلوس' ),
                        '0 salon — pièce principale' => array( 'fr' => '0 salon — pièce principale', 'en' => '0 living rooms — main room', 'ar' => 'دون غرفة جلوس — الغرفة الرئيسية' ),
                        '1 salon' => array( 'fr' => '1 salon', 'en' => '1 living room', 'ar' => 'غرفة جلوس واحدة' ),
                        '2 salons' => array( 'fr' => '2 salons', 'en' => '2 living rooms', 'ar' => 'غرفتا جلوس' ),
                        '3 salons ou plus' => array( 'fr' => '3 salons ou plus', 'en' => '3 living rooms or more', 'ar' => '3 غرف جلوس أو أكثر' ),
                        'Nombre de salles de bains' => array( 'fr' => 'Nombre de salles de bains', 'en' => 'Bathrooms', 'ar' => 'عدد الحمامات' ),
                        '1 salle de bains' => array( 'fr' => '1 salle de bains', 'en' => '1 bathroom', 'ar' => 'حمام واحد' ),
                        '2 salles de bains' => array( 'fr' => '2 salles de bains', 'en' => '2 bathrooms', 'ar' => 'حمامان' ),
                        '3 salles de bains ou plus' => array( 'fr' => '3 salles de bains ou plus', 'en' => '3 bathrooms or more', 'ar' => '3 حمامات أو أكثر' ),
                        'Terrasse' => array( 'fr' => 'Terrasse', 'en' => 'Terrace', 'ar' => 'شرفة' ),
                        'Non' => array( 'fr' => 'Non', 'en' => 'No', 'ar' => 'لا' ),
                        'Oui' => array( 'fr' => 'Oui', 'en' => 'Yes', 'ar' => 'نعم' ),
                        'Superficie de la terrasse (m²)' => array( 'fr' => 'Superficie de la terrasse (m²)', 'en' => 'Terrace area (m²)', 'ar' => 'مساحة الشرفة (م²)' ),
                        'Sans vis-à-vis' => array( 'fr' => 'Sans vis-à-vis', 'en' => 'No overlooking neighbours', 'ar' => 'بدون إطلالة مقابلة' ),
                        'Ensoleillement' => array( 'fr' => 'Ensoleillement', 'en' => 'Sunlight', 'ar' => 'التعرض للشمس' ),
                        'Ensoleillé le matin' => array( 'fr' => 'Ensoleillé le matin', 'en' => 'Morning sun', 'ar' => 'مشمس صباحاً' ),
                        'Ensoleillé l’après-midi' => array( 'fr' => 'Ensoleillé l’après-midi', 'en' => 'Afternoon sun', 'ar' => 'مشمس بعد الظهر' ),
                        'Toute la journée' => array( 'fr' => 'Toute la journée', 'en' => 'All day', 'ar' => 'طوال اليوم' ),
                        'Très peu' => array( 'fr' => 'Très peu', 'en' => 'Very little', 'ar' => 'قليل جداً' ),
                        'Description *' => array( 'fr' => 'Description *', 'en' => 'Description *', 'ar' => 'الوصف *' ),
                        'Décrivez votre bien : état, atouts, quartier, transports…' => array( 'fr' => 'Décrivez votre bien : état, atouts, quartier, transports…', 'en' => 'Describe your property: condition, features, neighbourhood, transport…', 'ar' => 'صف عقارك: حالته، مزاياه، الحي ووسائل النقل…' ),
                        'Vos photos' => array( 'fr' => 'Vos photos', 'en' => 'Your photos', 'ar' => 'صورك' ),
                        'Glissez vos photos ici' => array( 'fr' => 'Glissez vos photos ici', 'en' => 'Drag your photos here', 'ar' => 'اسحب صورك إلى هنا' ),
                        'ou cliquez pour parcourir (15 photos maximum, JPG/PNG)' => array( 'fr' => 'ou cliquez pour parcourir (15 photos maximum, JPG/PNG)', 'en' => 'or click to browse (15 photos maximum, JPG/PNG)', 'ar' => 'أو اضغط للتصفح (15 صورة كحد أقصى، JPG/PNG)' ),
                        'Vous (simple et rapide)' => array( 'fr' => 'Vous (simple et rapide)', 'en' => 'You (quick and easy)', 'ar' => 'بياناتك (بسهولة وسرعة)' ),
                        'Votre nom *' => array( 'fr' => 'Votre nom *', 'en' => 'Your name *', 'ar' => 'اسمك *' ),
                        'Jean Dupont' => array( 'fr' => 'Jean Dupont', 'en' => 'John Smith', 'ar' => 'محمد العلوي' ),
                        'E-mail' => array( 'fr' => 'E-mail', 'en' => 'Email', 'ar' => 'البريد الإلكتروني' ),
                        'vous@exemple.com' => array( 'fr' => 'vous@exemple.com', 'en' => 'you@example.com', 'ar' => 'you@example.com' ),
                        'Téléphone' => array( 'fr' => 'Téléphone', 'en' => 'Phone', 'ar' => 'الهاتف' ),
                        '06 12 34 56 78' => array( 'fr' => '06 12 34 56 78', 'en' => '+1 555 123 4567', 'ar' => '06 12 34 56 78' ),
                        'Votre téléphone est requis pour demander la validation via WhatsApp. Votre e-mail reste facultatif.' => array( 'fr' => 'Votre téléphone est requis pour demander la validation via WhatsApp. Votre e-mail reste facultatif.', 'en' => 'Your phone number is required for WhatsApp validation. Email is optional.', 'ar' => 'رقم الهاتف مطلوب لطلب التحقق عبر واتساب. البريد الإلكتروني اختياري.' ),
                        'Qui êtes-vous ?' => array( 'fr' => 'Qui êtes-vous ?', 'en' => 'Who are you?', 'ar' => 'من أنت؟' ),
                        'Vous êtes' => array( 'fr' => 'Vous êtes', 'en' => 'You are', 'ar' => 'أنت' ),
                        'Propriétaire' => array( 'fr' => 'Propriétaire', 'en' => 'Owner', 'ar' => 'مالك' ),
                        'Je vends ou loue mon bien' => array( 'fr' => 'Je vends ou loue mon bien', 'en' => 'I am selling or renting my property', 'ar' => 'أبيع أو أؤجر عقاري' ),
                        'Propriétaire' => array( 'fr' => 'Propriétaire', 'en' => 'Owner', 'ar' => 'المالك' ),
                        'Je gère pour quelqu’un' => array( 'fr' => 'Je gère pour quelqu’un', 'en' => 'I manage a property for someone else', 'ar' => 'أدير عقاراً لشخص آخر' ),
                        'Après l’enregistrement, vous enverrez un message WhatsApp prérempli. L’équipe vérifiera ce message avant de mettre l’annonce en ligne.' => array( 'fr' => 'Après l’enregistrement, vous enverrez un message WhatsApp prérempli. L’équipe vérifiera ce message avant de mettre l’annonce en ligne.', 'en' => 'After submission, you will send a pre-filled WhatsApp message. Our team will review it before publishing the listing.', 'ar' => 'بعد الإرسال، سترسل رسالة واتساب جاهزة. سيتحقق فريقنا منها قبل نشر الإعلان.' ),
                        'Demander la validation WhatsApp' => array( 'fr' => 'Demander la validation WhatsApp', 'en' => 'Request WhatsApp validation', 'ar' => 'طلب التحقق عبر واتساب' ),
                );
        }

}

